model_name: avb
hyperparameters:
  lr: 1e-4
  z_dim: 64
  lr_disc: 1e-3
  beta: 1
dataset: celeba
logger_path: runs/celeba_avb
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 5