model_name: btcvae
hyperparameters:
  lr: 1e-4
  z_dim: 64
  beta: 2.0
dataset: celeba
logger_path: runs/celeba_btcvae
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10