model_name: bvae
hyperparameters:
  lr: 1e-4
  z_dim: 64
  beta: 0.1
dataset: celeba
logger_path: runs/celeba_bvae
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10