model_name: dipvaeii
hyperparameters:
  lr: 1e-4
  z_dim: 64
  ld: 1
  lod: 10
dataset: celeba
logger_path: runs/celeba_dipvaeii
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10