model_name: factorvae
hyperparameters:
  lr: 1e-4
  lr_disc: 1e-3
  z_dim: 64
  gamma: 0.1
dataset: celeba
logger_path: runs/celeba_factorvae
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10