model_name: geco
hyperparameters:
  lr: 1e-4
  z_dim: 64
  tolerance: 10
  momentum: 0.99
  lbd_step: 100
dataset: celeba
logger_path: runs/celeba_geco
batch_size: 64
cuda_sync: false
very_verbose: true
epochs: 150