model_name: guidedvae
hyperparameters:
  lr: 1e-4
  z_dim: 64
  z_def_dim: 32
dataset: celeba
logger_path: runs/celeba_guidedvae
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10