model_name: laddervae
hyperparameters:
  lr: 1e-4
  z_dim: 64
  num_layers: 3
  batchnorm_latent: True
  warmup: True
dataset: celeba
logger_path: runs/celeba_laddervae
batch_size: 64
cuda_sync: false
very_verbose: true
epochs: 100