model_name: vamppriorvae
hyperparameters:
  lr: 1e-4
  z_dim: 64
  num_pseudo_inputs: 500
dataset: celeba
logger_path: runs/celeba_vampprior
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10