model_name: vitae
hyperparameters:
  lr: 1e-4
  z_dim: 64
  zp_dim: 62
dataset: celeba
logger_path: runs/celeba_vitae
batch_size: 64
cuda_sync: false
very_verbose: true
until_convergence: true
patience: 10